import express from "express";
import { body } from "express-validator";
import { register, registerAdmin, login, logout, getMe } from "../controllers/authController.js";
import { protect } from "../middleware/authMiddleware.js";
import { validate } from "../middleware/validate.js";
const router = express.Router();
router.post("/register", body("name").trim().notEmpty(), body("email").isEmail().normalizeEmail(), body("password").isLength({ min: 6 }), validate, register);
router.post("/register-admin", registerAdmin);
router.post("/login", body("email").isEmail(), body("password").notEmpty(), validate, login);
router.post("/logout", logout);
router.get("/me", protect, getMe);
router.get("/admin", protect, (req, res, next) => req.user.role === "ADMIN" ? res.json({ message: "Welcome Admin" }) : res.status(403).json({ message: "Access denied" }));
export default router;
